name: Update AWS Event Names

on:
  schedule:
    - cron: '*/15 * * * *' #Runs every 15 minutes
  workflow_dispatch:

jobs:
  check_for_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout self
        uses: actions/checkout@v2

      - name: Checkout TryTryAgain aws-iam-actions
        uses: actions/checkout@v2
        with:
          repository: TryTryAgain/aws-iam-actions-list
          path: monitored-repo
          ref: master

      - name: Run Python script
        run: |
          echo "Running Python script"
          python3 script.py