name: Update AWS Event Names

on:
  schedule:
    - cron: '0 */6 * * *' #Runs every 6 hours
  workflow_dispatch:

jobs:
  check_for_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout self
        uses: actions/checkout@v2

      - name: Run Python script
        run: |
          echo "Running update script"
          python3 update.py
      
      - name: Configure Git
        run: |
          git config --global user.name 'auto-updater[github-actions-bot]'
    
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update all-aws-events.txt with new AWS events"
          git push origin main
