name: Update AWS Event Names

on:
  schedule:
    - cron: '*/15 * * * *' #Runs every 15 minutes
  workflow_dispatch:

jobs:
  check_for_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout self
        uses: actions/checkout@v2

      - name: Checkout TryTryAgain aws-iam-actions
        uses: actions/checkout@v2
        with:
          repository: TryTryAgain/aws-iam-actions-list
          path: monitored-repo
          ref: master

      - name: Compare commit hashes
        id: check
        run: |
          echo "Fetching latest commit hash"
          cd monitored-repo
          latest_commit=$(git rev-parse HEAD)
          echo "Latest commit: $latest_commit"
          echo "::set-output name=latest_commit::$latest_commit"
          echo "Storing hash in a file for state management"
          if [ -f ../latest_commit.txt ]; then
            previous_commit=$(cat ../latest_commit.txt)
            echo "Previous commit: $previous_commit"
          else
            previous_commit=""
          fi
          echo "$latest_commit" > ../latest_commit.txt
          if [ "$latest_commit" = "$previous_commit" ]; then
            echo "No changes detected"
            exit 0
          else
            echo "Changes detected"
          fi

      - name: Run Python script
        run: |
          echo "Running update script"
          python3 update.py
      
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create a new branch
        run: |
          git checkout -b update-swapped-actions

      - name: Add and commit changes
        run: |
          git add swapped-actions.txt
          git commit -m "Update swapped-actions.txt with swapped lines"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-swapped-actions

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-swapped-actions
          base: main
          title: "Update swapped-actions.txt"
          body: "Automatically generated by GitHub Actions"