name: Update AWS Event Names

on:
  schedule:
    - cron: '0 */6 * * *' #Runs every 15 minutes
  workflow_dispatch:

jobs:
  check_for_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout self
        uses: actions/checkout@v2

      - name: Run Python script
        run: |
          echo "Running update script"
          python3 update.py
      
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push changes
        run: |
          git add all-aws-events.txt
          git commit -m "Update all-aws-events.txt with new AWS events"
          git push origin main